# Generated by Django 4.1.1 on 2022-11-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userFacebook",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="userInsta",
            field=models.TextField(blank=True, null=True),
        ),
    ]
