# Generated by Django 4.1.1 on 2022-11-01 03:27

from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0002_alter_user_userfacebook_alter_user_userinsta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userCV",
            field=models.FileField(
                blank=True, null=True, upload_to=userProfile.models.upload_file_perUser
            ),
        ),
    ]
