# Generated by Django 4.1.1 on 2022-11-01 05:26

from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0003_alter_user_usercv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userDisplay",
            field=models.ImageField(
                upload_to=userProfile.models.upload_profile_perUser
            ),
        ),
    ]
