# Generated by Django 4.1.1 on 2022-11-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0004_alter_user_userdisplay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="userCV",
        ),
    ]
